// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleApp08__EF__CdF_.DatabaseLayer;

#nullable disable

namespace SimpleApp08__EF__CdF_.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240503000124_Hand")]
    partial class Hand
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimpleApp08__EF__CdF_.DatabaseLayer.Models.Doctor", b =>
                {
                    b.Property<int>("IdDoctor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDoctor"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.HasKey("IdDoctor")
                        .HasName("Doktor_pk");

                    b.ToTable("Doktor", (string)null);

                    b.HasData(
                        new
                        {
                            IdDoctor = 1,
                            Email = "kn@wp.pl",
                            FirstName = "Krzysztof",
                            LastName = "Nowak"
                        },
                        new
                        {
                            IdDoctor = 2,
                            Email = "wc@wp.pl",
                            FirstName = "Waldemar",
                            LastName = "Cegliński"
                        },
                        new
                        {
                            IdDoctor = 3,
                            Email = "kn@wp.pl",
                            FirstName = "Aadrzej",
                            LastName = "Chlebowski"
                        });
                });

            modelBuilder.Entity("SimpleApp08__EF__CdF_.DatabaseLayer.Models.Medicament", b =>
                {
                    b.Property<int>("IdMedicament")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedicament"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.HasKey("IdMedicament")
                        .HasName("Medicament_pk");

                    b.ToTable("Medicament", (string)null);

                    b.HasData(
                        new
                        {
                            IdMedicament = 1,
                            Description = "Random ...",
                            Name = "Xanax",
                            Type = "Rand 1"
                        },
                        new
                        {
                            IdMedicament = 2,
                            Description = "Random ...",
                            Name = "Linex",
                            Type = "Rand 2"
                        },
                        new
                        {
                            IdMedicament = 3,
                            Description = "Random ...",
                            Name = "Woda Słona",
                            Type = "Rand 3"
                        });
                });

            modelBuilder.Entity("SimpleApp08__EF__CdF_.DatabaseLayer.Models.Patient", b =>
                {
                    b.Property<int>("IdPatient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPatient"));

                    b.Property<DateOnly>("Birthdate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.HasKey("IdPatient")
                        .HasName("Patient_pk");

                    b.ToTable("Pacjent", (string)null);

                    b.HasData(
                        new
                        {
                            IdPatient = 1,
                            Birthdate = new DateOnly(1970, 1, 12),
                            FirstName = "Dariusz",
                            LastName = "Chuchrowski"
                        },
                        new
                        {
                            IdPatient = 2,
                            Birthdate = new DateOnly(1980, 5, 17),
                            FirstName = "Damian",
                            LastName = "Bystroń"
                        },
                        new
                        {
                            IdPatient = 3,
                            Birthdate = new DateOnly(1992, 9, 22),
                            FirstName = "Anna",
                            LastName = "Bryłka"
                        });
                });

            modelBuilder.Entity("SimpleApp08__EF__CdF_.DatabaseLayer.Models.Prescription", b =>
                {
                    b.Property<int>("IdPrescription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrescription"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("IdDoctor")
                        .HasColumnType("int");

                    b.Property<int>("IdPatient")
                        .HasColumnType("int");

                    b.HasKey("IdPrescription")
                        .HasName("Prescription_pk");

                    b.HasIndex("IdDoctor");

                    b.HasIndex("IdPatient");

                    b.ToTable("Recepta", (string)null);

                    b.HasData(
                        new
                        {
                            IdPrescription = 1,
                            Date = new DateOnly(2024, 5, 3),
                            DueDate = new DateOnly(2024, 5, 13),
                            IdDoctor = 1,
                            IdPatient = 1
                        },
                        new
                        {
                            IdPrescription = 2,
                            Date = new DateOnly(2024, 5, 3),
                            DueDate = new DateOnly(2024, 5, 13),
                            IdDoctor = 1,
                            IdPatient = 2
                        });
                });

            modelBuilder.Entity("SimpleApp08__EF__CdF_.DatabaseLayer.Models.Prescription", b =>
                {
                    b.HasOne("SimpleApp08__EF__CdF_.DatabaseLayer.Models.Doctor", "Doctor")
                        .WithMany("Prescriptions")
                        .HasForeignKey("IdDoctor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Prescription_Doctor");

                    b.HasOne("SimpleApp08__EF__CdF_.DatabaseLayer.Models.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("IdPatient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Prescription_Patient");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SimpleApp08__EF__CdF_.DatabaseLayer.Models.Doctor", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("SimpleApp08__EF__CdF_.DatabaseLayer.Models.Patient", b =>
                {
                    b.Navigation("Prescriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
