// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleApp06__EF__CdF_.DatabaseLayer;

#nullable disable

namespace SimpleApp06__EF__CdF_.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240502065219_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimpleApp06__EF__CdF_.DatabaseLayer.Car", b =>
                {
                    b.Property<int>("IdCar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCar"));

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar");

                    b.Property<int>("PropductionYear")
                        .HasColumnType("int");

                    b.HasKey("IdCar")
                        .HasName("Car_pk");

                    b.ToTable("Samochody", (string)null);

                    b.HasData(
                        new
                        {
                            IdCar = 1,
                            Make = "Poland",
                            PropductionYear = 1990
                        },
                        new
                        {
                            IdCar = 2,
                            Make = "Germany",
                            PropductionYear = 1991
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
