//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BialaListaVat {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BialaListaVat.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem z deserializacją .
        /// </summary>
        internal static string DeserializationProblem {
            get {
                return ResourceManager.GetString("DeserializationProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny URL.
        /// </summary>
        internal static string IncorrectUrl {
            get {
                return ResourceManager.GetString("IncorrectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MessageForClientOk {
            get {
                return ResourceManager.GetString("MessageForClientOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error.
        /// </summary>
        internal static string MessageForClientServerError {
            get {
                return ResourceManager.GetString("MessageForClientServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa wartość w rmach Enum statusów VAT.
        /// </summary>
        internal static string NewEnumStatusVat {
            get {
                return ResourceManager.GetString("NewEnumStatusVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy status VAT, uzupełnij kod.
        /// </summary>
        internal static string NewValueStatusVat {
            get {
                return ResourceManager.GetString("NewValueStatusVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP Niepoprawny, składa z 10 cyfr.
        /// </summary>
        internal static string NipExeption {
            get {
                return ResourceManager.GetString("NipExeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGON niepoprawny, składa sie z lub 14 cyfr.
        /// </summary>
        internal static string RegonExeption {
            get {
                return ResourceManager.GetString("RegonExeption", resourceCulture);
            }
        }
    }
}
