// <auto-generated />
using System;
using MAS05.DatabaseLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MAS05.Migrations
{
    [DbContext(typeof(BeeDBContext))]
    [Migration("20240512075941_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MAS05.DatabaseLayer.Models.Bee", b =>
                {
                    b.Property<int>("IdBee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBee"));

                    b.Property<DateOnly>("BirthDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Imie");

                    b.HasKey("IdBee")
                        .HasName("Pszczola_pk");

                    b.ToTable("Pszczola", (string)null);

                    b.HasData(
                        new
                        {
                            IdBee = 1,
                            BirthDate = new DateOnly(2024, 5, 20),
                            Name = "Bzzz"
                        },
                        new
                        {
                            IdBee = 2,
                            BirthDate = new DateOnly(2024, 5, 15),
                            Name = "Bzzzaa"
                        },
                        new
                        {
                            IdBee = 3,
                            BirthDate = new DateOnly(2024, 5, 12),
                            Name = "Bzzzuu"
                        });
                });

            modelBuilder.Entity("MAS05.DatabaseLayer.Models.BeeHome", b =>
                {
                    b.Property<int>("IdBeeHome")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBeeHome"));

                    b.Property<int>("MaxSize")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Nazwa");

                    b.HasKey("IdBeeHome")
                        .HasName("PszcołkiDomek_pk");

                    b.ToTable("PszcołkiDomek", (string)null);

                    b.HasData(
                        new
                        {
                            IdBeeHome = 1,
                            MaxSize = 30000,
                            Name = "Domek 1"
                        },
                        new
                        {
                            IdBeeHome = 2,
                            MaxSize = 60000,
                            Name = "Domek 2"
                        },
                        new
                        {
                            IdBeeHome = 3,
                            MaxSize = 45000,
                            Name = "Domek 1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
