// <auto-generated />
using System;
using MAS05.DatabaseLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MAS05.Migrations
{
    [DbContext(typeof(BeeDBContext))]
    [Migration("20240519214706_Hand")]
    partial class Hand
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MAS05.DatabaseLayer.Models.Bee", b =>
                {
                    b.Property<int>("IdBee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBee"));

                    b.Property<DateOnly>("BirthDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateOnly?>("DateDeath")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Imie");

                    b.HasKey("IdBee")
                        .HasName("Pszczola_pk");

                    b.ToTable("Pszczola", (string)null);

                    b.HasData(
                        new
                        {
                            IdBee = 1,
                            BirthDate = new DateOnly(2024, 5, 20),
                            Name = "Bzzz"
                        },
                        new
                        {
                            IdBee = 2,
                            BirthDate = new DateOnly(2024, 5, 15),
                            Name = "Bzzzaa"
                        },
                        new
                        {
                            IdBee = 3,
                            BirthDate = new DateOnly(2024, 5, 12),
                            Name = "Bzzzuu"
                        });
                });

            modelBuilder.Entity("MAS05.DatabaseLayer.Models.BeeHome", b =>
                {
                    b.Property<int>("IdBeeHome")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBeeHome"));

                    b.Property<int>("MaxSize")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Nazwa");

                    b.HasKey("IdBeeHome")
                        .HasName("PszcołkiDomek_pk");

                    b.ToTable("PszcołkiDomek", (string)null);

                    b.HasData(
                        new
                        {
                            IdBeeHome = 1,
                            MaxSize = 30000,
                            Name = "Domek 1"
                        },
                        new
                        {
                            IdBeeHome = 2,
                            MaxSize = 60000,
                            Name = "Domek 2"
                        },
                        new
                        {
                            IdBeeHome = 3,
                            MaxSize = 45000,
                            Name = "Domek 3"
                        });
                });

            modelBuilder.Entity("MAS05.DatabaseLayer.Models.BeeHomeAndBee", b =>
                {
                    b.Property<int>("IdBee")
                        .HasColumnType("int");

                    b.Property<int>("IdBeeHome")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateTo")
                        .HasColumnType("date");

                    b.HasKey("IdBee", "IdBeeHome")
                        .HasName("PszczolkiDomPszczolka_pk");

                    b.HasIndex("IdBeeHome");

                    b.ToTable("PszczolkiDomPszczolka", (string)null);
                });

            modelBuilder.Entity("MAS05.DatabaseLayer.Models.BeeIntelligence", b =>
                {
                    b.Property<int>("IdBee")
                        .HasColumnType("int");

                    b.Property<int>("Distance")
                        .HasColumnType("int")
                        .HasColumnName("Dystans");

                    b.HasKey("IdBee")
                        .HasName("PszczolaWywiadowaca_pk");

                    b.ToTable("PszczolaWywiadowaca", (string)null);

                    b.HasData(
                        new
                        {
                            IdBee = 2,
                            Distance = 3
                        },
                        new
                        {
                            IdBee = 3,
                            Distance = 5
                        });
                });

            modelBuilder.Entity("MAS05.DatabaseLayer.Models.BeeSecurity", b =>
                {
                    b.Property<int>("IdBee")
                        .HasColumnType("int");

                    b.Property<int>("Power")
                        .HasColumnType("int")
                        .HasColumnName("Sila");

                    b.HasKey("IdBee")
                        .HasName("PszczolaOchroniarz_pk");

                    b.ToTable("PszczolaOchroniarz", (string)null);

                    b.HasData(
                        new
                        {
                            IdBee = 1,
                            Power = 10
                        },
                        new
                        {
                            IdBee = 2,
                            Power = 15
                        });
                });

            modelBuilder.Entity("MAS05.DatabaseLayer.Models.BeeHomeAndBee", b =>
                {
                    b.HasOne("MAS05.DatabaseLayer.Models.Bee", "Bee")
                        .WithMany("BeeHomeAndBees")
                        .HasForeignKey("IdBee")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("PszczolkiDomPszczolka_Pszczolka");

                    b.HasOne("MAS05.DatabaseLayer.Models.BeeHome", "BeeHome")
                        .WithMany("BeeHomeAndBees")
                        .HasForeignKey("IdBeeHome")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("PszczolkiDomPszczolka_PszczolkiDom");

                    b.Navigation("Bee");

                    b.Navigation("BeeHome");
                });

            modelBuilder.Entity("MAS05.DatabaseLayer.Models.BeeIntelligence", b =>
                {
                    b.HasOne("MAS05.DatabaseLayer.Models.Bee", "Bee")
                        .WithOne("BeeIntelligence")
                        .HasForeignKey("MAS05.DatabaseLayer.Models.BeeIntelligence", "IdBee")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("PszczolaWywiadowaca_Pszczola");

                    b.Navigation("Bee");
                });

            modelBuilder.Entity("MAS05.DatabaseLayer.Models.BeeSecurity", b =>
                {
                    b.HasOne("MAS05.DatabaseLayer.Models.Bee", "Bee")
                        .WithOne("BeeSecurity")
                        .HasForeignKey("MAS05.DatabaseLayer.Models.BeeSecurity", "IdBee")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("PszczolaOchroniarz_Pszczola");

                    b.Navigation("Bee");
                });

            modelBuilder.Entity("MAS05.DatabaseLayer.Models.Bee", b =>
                {
                    b.Navigation("BeeHomeAndBees");

                    b.Navigation("BeeIntelligence");

                    b.Navigation("BeeSecurity");
                });

            modelBuilder.Entity("MAS05.DatabaseLayer.Models.BeeHome", b =>
                {
                    b.Navigation("BeeHomeAndBees");
                });
#pragma warning restore 612, 618
        }
    }
}
